### ISSUE TITLE
question: golang client

### ISSUE THREAD

**Issue by joeblew99** [rgraphql/magellan#12]
this is pretty cool.
1st question.
Can i use magellan as a golang client ? I dont need a web client for my projects.

2nd question.
I am using QUIC for fast streaming updates. 
Its very easy to use with golang.
Example: https://github.com/lucas-clemente/quic-go/blob/master/example/main.go
It can use protobuffers as the serialisation.
Only google chrome can handele QUIC if you want to use a web browser, but its ging through IETF but that does not mean other browsers will adopt it of course.
https://datatracker.ietf.org/wg/quic/charter/

**Comment by paralin** [comment]
1. Not yet. I haven't written a Go client, and I'd probably name it something else and put it in a separate repo as is the style with Soyuz. I can build that sometime soon, but I'd like to get everything ironed out with the JS client first to make sure there's no protocol changes I'll need to track between multiple languages. 
2. Quic is a transport protocol. I like it a lot. You can send the rgraphql packets over whatever transport you want, so quic is perfect.
