### ISSUE TITLE
Implementation that does not require code generation

### ISSUE THREAD

**Issue by gedw99** [rgraphql/magellan#16]
Hey @paralin 
Been trying this out and generating golang clients just to play around with its concepts.

there is a similar project that does not require any code generation that I think is quite interesting but may not fit your use case . I use it for some projects and it pretty awesome . 

https://github.com/dosco/graphjin

It works with PostgreSQL but it’s logic of how it works is not specific to that db . I have Ben thinking about adapting it for genji but am too busy right now. 

Under the hood it polls the db , running all the equivalent graphql subscriptions and returns the graphql diff equivalent 

the web gui is cool because you see your graphql schema in real time. All you do is add a table to the DB and baddy boom you have extending your public graphql schema . 

I will probably merge it with genji at sometime so let me know if you think this is worthwhile to Magellan

**Comment by paralin** [comment]
Thanks for the link, Will read about graphjin.

It looks like it requires a DB backend and uses mostly SQL queries.

That's definitely a interesting approach but magellan is mainly oriented towards fetching data from any Go codebase regardless of what the Go codebase queries underneath.

So diferent use cases for sure.

Thanks again, I will read into it more.

**Comment by gedw99** [comment]
Yeah quite different I know .

Magellan required code gen . Graphjin does not .

 Am using it quite a bit. But have extended it to use jsonschema to model the db so that the json schema can be used throughout the stack for validation logic
